start-at-login = true
key-mapping.preset = 'qwerty'

after-login-command = []
after-startup-command = []

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

default-root-container-layout = 'tiles'
default-root-container-orientation = 'horizontal'

on-focused-monitor-changed = 'move-mouse monitor-lazy-center'
on-focus-changed = 'move-mouse window-lazy-center'

accordion-padding = 60

[gaps]

inner.horizontal = 16
inner.vertical =   16
outer.left =       16
outer.bottom =     16
outer.top =        16
outer.right =      16

[mode.main.binding]

ctrl-alt-cmd-shift-minus = 'resize smart -50'
ctrl-alt-cmd-shift-equal = 'resize smart +50'
ctrl-alt-cmd-shift-f = 'fullscreen'

ctrl-alt-cmd-shift-s = 'exec-and-forget screencapture -i -c'

ctrl-alt-cmd-shift-h = 'focus left'
ctrl-alt-cmd-shift-j = 'focus down'
ctrl-alt-cmd-shift-k = 'focus up'
ctrl-alt-cmd-shift-l = 'focus right'

ctrl-alt-cmd-shift-backspace = 'workspace-back-and-forth'

ctrl-alt-cmd-shift-w = 'mode win'
ctrl-alt-cmd-shift-o = 'mode open'

ctrl-alt-cmd-shift-z = 'workspace Z --auto-back-and-forth'
ctrl-alt-cmd-shift-x = 'workspace X --auto-back-and-forth'
ctrl-alt-cmd-shift-c = 'workspace C --auto-back-and-forth'
ctrl-alt-cmd-shift-v = 'workspace V --auto-back-and-forth'
ctrl-alt-cmd-shift-b = 'workspace B --auto-back-and-forth'
ctrl-alt-cmd-shift-n = 'workspace N --auto-back-and-forth'
ctrl-alt-cmd-shift-m = 'workspace M --auto-back-and-forth'

[mode.win.binding]

esc = ['reload-config', 'mode main']
enter = ['reload-config', 'mode main']

h = ['move left', 'mode main']
j = ['move down', 'mode main']
k = ['move up', 'mode main']
l = ['move right', 'mode main']

shift-h = ['join-with left', 'mode main']
shift-j = ['join-with down', 'mode main']
shift-k = ['join-with up', 'mode main']
shift-l = ['join-with right', 'mode main']

f = ['layout floating tiling', 'mode main']

t = ['layout tiles horizontal vertical', 'mode main']
a = ['layout accordion horizontal vertical', 'mode main']

ctrl-h = ['move-workspace-to-monitor left', 'mode main']
ctrl-j = ['move-workspace-to-monitor down', 'mode main']
ctrl-k = ['move-workspace-to-monitor up', 'mode main']
ctrl-l = ['move-workspace-to-monitor right', 'mode main']

z = ['move-node-to-workspace Z', 'workspace Z', 'mode main']
x = ['move-node-to-workspace X', 'workspace X', 'mode main']
c = ['move-node-to-workspace C', 'workspace C', 'mode main']
v = ['move-node-to-workspace V', 'workspace V', 'mode main']
b = ['move-node-to-workspace B', 'workspace B', 'mode main']
n = ['move-node-to-workspace N', 'workspace N', 'mode main']
m = ['move-node-to-workspace M', 'workspace M', 'mode main']

[mode.open.binding]

esc = 'mode main'

b = ['exec-and-forget open -a Arc', 'mode main']
c = ['exec-and-forget open -a Neovide', 'mode main']
m = ['exec-and-forget open -a Telegram', 'mode main']
n = ['exec-and-forget open -a Obsidian', 'mode main']
s = ['exec-and-forget open -a Settings', 'mode main']
t = ['exec-and-forget open -a Ghostty || open -a Alacritty || open -a Terminal', 'mode main']

[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
run = ['layout tiling', 'move-node-to-workspace B']

[[on-window-detected]]
if.app-id = 'app.zen-browser.zen'
run = ['layout tiling', 'move-node-to-workspace B']

[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = ['layout tiling', 'move-node-to-workspace B']

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = ['layout tiling', 'move-node-to-workspace B']

[[on-window-detected]]
if.app-id = 'ru.yandex.desktop.yandex-browser'
run = ['layout tiling', 'move-node-to-workspace B']

[[on-window-detected]]
if.app-id = 'org.qutebrowser.qutebrowser'
run = ['layout tiling', 'move-node-to-workspace B']

[[on-window-detected]]
if.app-id = 'com.neovide.neovide'
run = ['layout tiling', 'move-node-to-workspace C']

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = ['layout tiling', 'move-node-to-workspace C']

[[on-window-detected]]
if.app-id = 'org.alacritty'
run = ['layout tiling', 'move-node-to-workspace C']

[[on-window-detected]]
if.app-id = 'com.apple.Terminal'
run = ['layout tiling', 'move-node-to-workspace C']

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = ['layout tiling', 'move-node-to-workspace C']

[[on-window-detected]]
if.app-id = 'com.jetbrains.intellij.ce'
run = ['layout tiling', 'move-node-to-workspace C']

[[on-window-detected]]
if.app-id = 'com.jetbrains.intellij'
run = ['layout tiling', 'move-node-to-workspace C']

[[on-window-detected]]
if.app-id = 'com.google.android.studio'
run = ['layout tiling', 'move-node-to-workspace C']

[[on-window-detected]]
if.app-id = 'ru.keepcoder.Telegram'
run = ['layout tiling', 'move-node-to-workspace M']

[[on-window-detected]]
if.app-id = 'ru.yandex.desktop.music'
run = ['layout tiling', 'move-node-to-workspace M']

[[on-window-detected]]
if.app-id = 'md.obsidian'
run = ['layout tiling', 'move-node-to-workspace N']

[[on-window-detected]]
if.app-id = 'com.apple.Notes'
run = ['layout tiling', 'move-node-to-workspace N']

[[on-window-detected]]
if.app-id = 'com.apple.reminders'
run = ['layout tiling', 'move-node-to-workspace N']

[[on-window-detected]]
if.app-id = 'us.zoom.xos'
run = ['layout tiling', 'move-node-to-workspace Z']

[[on-window-detected]]
if.app-id = 'ru.yandex.desktop.telemost'
run = ['layout tiling', 'move-node-to-workspace Z']

[[on-window-detected]]
if.app-id = 'com.apple.FaceTime'
run = ['layout tiling', 'move-node-to-workspace Z']

[[on-window-detected ]]
if.app-id = 'com.hnc.Discord'
run = ['layout tiling', 'move-node-to-workspace Z']

[[on-window-detected]]
if.app-id = 'com.microsoft.Word'
run = ['layout tiling', 'move-node-to-workspace V']

[[on-window-detected]]
if.app-id = 'com.microsoft.Excel'
run = ['layout tiling', 'move-node-to-workspace V']

[[on-window-detected]]
if.app-id = 'com.microsoft.Powerpoint'
run = ['layout tiling', 'move-node-to-workspace V']

[[on-window-detected]]
if.app-id = 'com.apple.iWork.Keynote'
run = ['layout tiling', 'move-node-to-workspace V']

[[on-window-detected]]
if.app-id = 'org.audacityteam.audacity'
run = ['layout tiling', 'move-node-to-workspace V']

[[on-window-detected]]
if.app-id = 'org.blenderfoundation.blender'
run = ['layout tiling', 'move-node-to-workspace V']

[[on-window-detected]]
if.app-id = 'nightradio.SunVox'
run = ['layout tiling', 'move-node-to-workspace V']

[[on-window-detected]]
if.app-id = 'com.figma.Desktop'
run = ['layout tiling', 'move-node-to-workspace V']

[[on-window-detected]]
if.app-id = 'com.apple.ActivityMonitor'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'e.AmneziaVPN'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.Preview'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'ru.yandex.desktop.disk2'
run = ['layout floating']

