[settings]
trusted_config_paths = ["~/.config"]

idiomatic_version_file_enable_tools = ["node", "python"]

python_venv_auto_create = true

[tools]
deno = "latest"
node = "latest"
python = "3.14"
uv = "latest"

fzf = "latest"
jq = "latest"
just = "latest"
neovim = "latest"
opencode = "latest"
ripgrep = "latest"
starship = "latest"
tree-sitter = "latest"
yazi = "latest"
zoxide = "latest"
